import { useState, useEffect } from "react";
import { useNavigate } from "react-router-dom";
import { X, Copy, RefreshCw, Loader2, Sparkles, Check } from "lucide-react";
import type { Channel } from "../domain/channel";
import {
  generateAutoIdeaAndScripts,
  generateDetailedScripts,
  type AutoGeneratedResult,
  type GenerationResponse
} from "../services/openaiScriptGenerator";
import {
  fetchLatestVideoToDrive,
  fetchAndSaveToServer,
  sendPromptToSyntx
} from "../api/telegram";
import { useChannelStore } from "../stores/channelStore";
import { useAuthStore } from "../stores/authStore";
import { updatePreferenceIndex, getCurrentPreferenceVariant } from "../utils/preferencesUtils";

interface AIAutoGenerateModalProps {
  isOpen: boolean;
  channel: Channel | null;
  onClose: () => void;
}

const AIAutoGenerateModal = ({
  isOpen,
  channel,
  onClose
}: AIAutoGenerateModalProps) => {
  const navigate = useNavigate();
  const { user } = useAuthStore((state) => ({ user: state.user }));
  const { updateChannel, fetchChannels, channels } = useChannelStore((state) => ({
    updateChannel: state.updateChannel,
    fetchChannels: state.fetchChannels,
    channels: state.channels
  }));
  const [loading, setLoading] = useState(false);
  const [error, setError] = useState<string | null>(null);
  const [result, setResult] = useState<AutoGeneratedResult | null>(null);
  const [detailedResult, setDetailedResult] =
    useState<GenerationResponse | null>(null);
  const [copied, setCopied] = useState(false);
  const [copiedScriptIndex, setCopiedScriptIndex] = useState<number | null>(
    null
  );
  const [copiedVideoPrompt, setCopiedVideoPrompt] = useState(false);
  const [copiedFileTitle, setCopiedFileTitle] = useState(false);
  const [syntxSendStatus, setSyntxSendStatus] = useState<
    "idle" | "loading" | "sent" | "error"
  >("idle");
  const [syntxError, setSyntxError] = useState<string | null>(null);
  const [driveStatus, setDriveStatus] = useState<
    "idle" | "loading" | "success" | "error" | "telegram_session_invalid"
  >("idle");
  const [driveMessage, setDriveMessage] = useState<string | null>(null);
  const [driveWebViewLink, setDriveWebViewLink] = useState<string | null>(null);

  useEffect(() => {
    if (isOpen && channel) {
      setError(null);
      setResult(null);
      setDetailedResult(null);
      setSyntxSendStatus("idle");
      setSyntxError(null);
      setDriveStatus("idle");
      setDriveMessage(null);
      setDriveWebViewLink(null);
      void handleGenerate();
    } else {
      setResult(null);
      setDetailedResult(null);
      setError(null);
      setSyntxSendStatus("idle");
      setSyntxError(null);
      setDriveStatus("idle");
      setDriveMessage(null);
      setDriveWebViewLink(null);
    }
    // eslint-disable-next-line react-hooks/exhaustive-deps
  }, [isOpen, channel?.id]);

  /**
   * Генерирует ИИ-идею и сценарии для канала.
   * 
   * АВТОРИЗАЦИЯ:
   * - Функции generateAutoIdeaAndScripts и generateDetailedScripts автоматически
   *   используют Firebase токен через callOpenAIProxy
   * - Требует авторизованного пользователя (проверяется через user?.uid)
   * 
   * ОБРАБОТКА ОШИБОК:
   * - Извлекает понятное сообщение из разных форматов ошибок
   * - Логирует ошибки в консоль для отладки
   * - Показывает пользователю понятное сообщение вместо [object Object]
   */
  const handleGenerate = async () => {
    if (!channel) {
      setError("Канал не выбран");
      return;
    }
    
    if (!user?.uid) {
      setError("Вы не авторизованы. Пожалуйста, войдите в систему.");
      return;
    }

    // Перезагружаем канал из store, чтобы получить актуальные preferences
    await fetchChannels(user.uid);
    const currentChannel = channels.find((c) => c.id === channel.id) || channel;

    // Логируем текущее состояние preferences
    if (currentChannel.preferences) {
      const selectedVariant = getCurrentPreferenceVariant(currentChannel.preferences);
      console.log("🔍 AIAutoGenerateModal - Current preferences:", {
        mode: currentChannel.preferences.mode,
        lastUsedIndex: currentChannel.preferences.lastUsedIndex,
        variantsCount: currentChannel.preferences.variants.length,
        variants: currentChannel.preferences.variants.map((v, i) => ({
          index: i,
          text: v.text.substring(0, 50) + "..."
        })),
        selectedVariant: selectedVariant.substring(0, 100) + "..."
      });
    }

    setLoading(true);
    setError(null);
    setResult(null);
    setDetailedResult(null);

    try {
      const mode = currentChannel.generationMode || "script";
      
      if (mode === "prompt" || mode === "video-prompt-only") {
        // Используем новую функцию для детальных сценариев или только videoPrompt
        // Запрос к /api/prompt/openai с автоматической авторизацией
        const generated = await generateDetailedScripts(currentChannel);
        setDetailedResult(generated);
      } else {
        // Старый формат для обратной совместимости
        // Запрос к /api/prompt/openai с автоматической авторизацией
        const generated = await generateAutoIdeaAndScripts(currentChannel);
        setResult(generated);
      }

      // Обновляем индекс preferences после успешной генерации
      if (currentChannel.preferences && currentChannel.preferences.mode === "cyclic") {
        const oldIndex = currentChannel.preferences.lastUsedIndex || 0;
        const updatedPreferences = updatePreferenceIndex(currentChannel.preferences);
        const newIndex = updatedPreferences?.lastUsedIndex || 0;
        
        // Обновляем только если индекс изменился
        if (oldIndex !== newIndex) {
          const updatedChannel = {
            ...currentChannel,
            preferences: updatedPreferences
          };
          await updateChannel(user.uid, updatedChannel);
          // Перезагружаем каналы после обновления
          await fetchChannels(user.uid);
          
          console.log("✅ AIAutoGenerateModal - Updated preferences index:", {
            oldIndex,
            newIndex,
            variantsCount: currentChannel.preferences.variants.length
          });
        }
      }
    } catch (err) {
      // Извлекаем понятное сообщение об ошибке из разных форматов
      let errorMessage = "Не удалось сгенерировать идею. Попробуйте ещё раз.";
      
      if (err instanceof Error) {
        errorMessage = err.message;
      } else if (err && typeof err === "object") {
        // Обработка ошибок из fetch/axios и других источников
        const errorObj = err as any;
        errorMessage =
          errorObj?.response?.data?.message ||
          errorObj?.response?.data?.error ||
          errorObj?.message ||
          errorObj?.error ||
          String(errorObj) ||
          errorMessage;
      } else if (typeof err === "string") {
        errorMessage = err;
      }
      
      // Логируем ошибку для отладки
      console.error("AI idea generation error:", err);
      
      setError(errorMessage);
    } finally {
      setLoading(false);
    }
  };

  const handleCopyAll = async () => {
    if (detailedResult) {
      // Копирование детальных сценариев
      const textToCopy = detailedResult.scenarios
        .map(
          (scenario) =>
            `${scenario.title} (${scenario.durationSeconds} сек):\n\n${scenario.steps
              .map(
                (step) =>
                  `${step.secondFrom}-${step.secondTo}с: ${step.description}${step.dialog.length > 0 ? `\n${step.dialog.map((d) => `${d.character}: "${d.text}"`).join("\n")}` : ""}`
              )
              .join("\n\n")}`
        )
        .join("\n\n---\n\n");

      try {
        await navigator.clipboard.writeText(textToCopy);
        setCopied(true);
        setTimeout(() => setCopied(false), 2000);
      } catch (err) {
        setError("Не удалось скопировать в буфер обмена");
      }
      return;
    }

    if (!result) {
      return;
    }

    const textToCopy = `ИДЕЯ РОЛИКА:\n${result.idea}\n\n${result.scripts
      .map((script, index) => `СЦЕНАРИЙ ${index + 1}:\n${script}`)
      .join("\n\n")}`;

    try {
      await navigator.clipboard.writeText(textToCopy);
      setCopied(true);
      setTimeout(() => setCopied(false), 2000);
    } catch (err) {
      setError("Не удалось скопировать в буфер обмена");
    }
  };

  const handleCopyVideoPrompt = async () => {
    if (!detailedResult?.videoPrompt) {
      return;
    }

    try {
      await navigator.clipboard.writeText(detailedResult.videoPrompt);
      setCopiedVideoPrompt(true);
      setTimeout(() => setCopiedVideoPrompt(false), 2000);
    } catch (err) {
      setError("Не удалось скопировать промпт в буфер обмена");
    }
  };

  const handleCopyFileTitle = async () => {
    if (!detailedResult?.fileTitle) {
      return;
    }

    try {
      await navigator.clipboard.writeText(detailedResult.fileTitle);
      setCopiedFileTitle(true);
      setTimeout(() => setCopiedFileTitle(false), 2000);
    } catch (err) {
      setError("Не удалось скопировать название в буфер обмена");
    }
  };

  const handleSendToSyntx = async () => {
    if (!detailedResult?.videoPrompt || !channel) {
      return;
    }

    setSyntxSendStatus("loading");
    setSyntxError(null);

    try {
      // Передаем channelId, чтобы backend мог определить, какой тип Telegram использовать
      await sendPromptToSyntx(detailedResult.videoPrompt, channel.id);
      setSyntxSendStatus("sent");
    } catch (err: any) {
      setSyntxSendStatus("error");
      
      const status = err?.response?.status || err?.response?.statusCode;
      const errorCode = err?.response?.data?.error;
      const errorMessage = err?.response?.data?.message;
      
      // Обработка ошибки 401 (неавторизован в приложении - это ошибка авторизации Firebase)
      if (status === 401) {
        // Проверяем, это ошибка авторизации приложения или Telegram
        if (errorCode === "Unauthorized" || errorMessage?.includes("token") || errorMessage?.includes("Authorization")) {
          setSyntxError("Сессия приложения истекла. Обновите страницу и войдите в аккаунт ещё раз.");
          console.error("401 Unauthorized (Firebase auth) при отправке в Syntx:", err?.response?.data);
          return;
        }
        // Если это TELEGRAM_SESSION_EXPIRED_NEED_RELOGIN, обрабатываем ниже как ошибку Telegram
      }
      
      // Обработка ошибок Telegram (не ошибки авторизации приложения)
      let userFriendlyMessage: string;
      
      if (errorCode === "TELEGRAM_SESSION_EXPIRED_NEED_RELOGIN") {
        userFriendlyMessage = "Не удалось отправить промпт в Syntx: сессия Telegram истекла. Отвяжите Telegram в настройках и привяжите снова.";
      } else if (errorCode === "TELEGRAM_USER_NOT_CONNECTED") {
        userFriendlyMessage = "Telegram не привязан. Привяжите Telegram в настройках аккаунта.";
      } else if (errorCode === "TELEGRAM_SESSION_NOT_INITIALIZED") {
        userFriendlyMessage = "Telegram сессия не инициализирована. Обратитесь к администратору.";
      } else if (errorCode === "SYNX_CHAT_ID_NOT_CONFIGURED") {
        userFriendlyMessage = "Настройки сервера не завершены. Обратитесь к администратору.";
      } else if (errorCode === "FAILED_TO_SEND_PROMPT") {
        userFriendlyMessage = errorMessage || "Не удалось отправить промпт. Попробуйте позже.";
      } else if (errorMessage) {
        userFriendlyMessage = errorMessage;
      } else if (err?.message) {
        userFriendlyMessage = err.message;
      } else {
        userFriendlyMessage = "Ошибка при отправке промпта в SyntX. Попробуйте позже.";
      }
      
      console.error("Ошибка при отправке в Syntx:", {
        status,
        errorCode,
        errorMessage,
        channelId: channel?.id,
        channelTransport: channel?.generationTransport,
        fullError: err
      });
      
      setSyntxError(userFriendlyMessage);
    }
  };

  const handleFetchVideoToDrive = async () => {
    if (!channel) return;

    setDriveStatus("loading");
    setDriveMessage(null);

    try {
      // Получаем название ролика из detailedResult.fileTitle
      const videoTitle = detailedResult?.fileTitle || null;

      // Используем новый эндпоинт для сохранения на сервер
      const result = await fetchAndSaveToServer(
        channel.id,
        undefined, // telegramMessageId - не передаём, ищем последнее видео
        videoTitle || undefined // Передаём название ролика для имени файла
      );

      if (result.status === "ok" || result.status === "success" || result.success === true) {
        setDriveStatus("success");
        setDriveMessage("🟢 Видео успешно сохранено на сервер");
      } else {
        setDriveStatus("error");
        setDriveMessage(
          result.message ||
            "Ошибка сервера при сохранении видео. Попробуйте позже."
        );
      }
    } catch (err: any) {
      setDriveStatus("error");
      
      const errorCode = err?.response?.data?.code || err?.response?.data?.error;
      const errorType = err?.response?.data?.errorType;
      const errorMessage = err?.response?.data?.message || err?.message;
      
      console.error("Ошибка при сохранении видео на сервер:", {
        status: err?.response?.status,
        errorCode,
        errorType,
        errorMessage,
        fullError: err
      });
      
      // ТОЧНАЯ проверка на TELEGRAM_SESSION_INVALID (только если backend явно вернул этот код)
      if (errorCode === "TELEGRAM_SESSION_INVALID") {
        setDriveMessage(
          "Не удалось забрать видео: сессия Telegram больше недействительна. " +
          "Зайдите в настройки аккаунта, отвяжите Telegram и привяжите его заново."
        );
        // Сохраняем флаг для показа кнопки перехода в настройки
        setDriveStatus("telegram_session_invalid");
        return;
      }
      
      
      // Обработка ошибок скачивания (все остальные ошибки Telegram)
      if (errorCode === "TELEGRAM_DOWNLOAD_FAILED" || errorMessage?.includes("TELEGRAM_DOWNLOAD")) {
        setDriveMessage(
          errorMessage || "Не удалось забрать видео из Telegram. Попробуйте ещё раз чуть позже или проверьте настройки."
        );
      } else if (errorMessage) {
        setDriveMessage(errorMessage);
      } else {
        setDriveMessage(
          "Ошибка при сохранении видео на сервер. Попробуйте позже."
        );
      }
    }
  };

  const handleCopyScript = async (scriptText: string, index: number) => {
    try {
      await navigator.clipboard.writeText(scriptText);
      setCopiedScriptIndex(index);
      setTimeout(() => setCopiedScriptIndex(null), 2000);
    } catch (err) {
      setError("Не удалось скопировать сценарий в буфер обмена");
    }
  };

  if (!isOpen || !channel) {
    return null;
  }

  const handleBackdropClick = (e: React.MouseEvent<HTMLDivElement>) => {
    if (e.target === e.currentTarget && !loading) {
      onClose();
    }
  };

  return (
    <div
      className="fixed inset-0 z-50 flex items-center justify-center bg-black/60 p-4"
      onClick={handleBackdropClick}
    >
      <div
        className="relative w-full max-w-4xl max-h-[90vh] overflow-y-auto rounded-2xl border border-white/10 bg-slate-900 text-white shadow-2xl"
        onClick={(e) => e.stopPropagation()}
      >
        {/* Header */}
        <div className="sticky top-0 z-10 flex items-center justify-between border-b border-white/10 bg-slate-900/95 backdrop-blur-sm px-6 py-4">
          <div className="flex items-center gap-3">
            <Sparkles className="h-5 w-5 text-brand-light" />
            <h2 className="text-xl font-semibold">
              Автоидея от ИИ для канала "{channel.name}"
            </h2>
          </div>
          <button
            type="button"
            onClick={onClose}
            className="rounded-lg p-2 text-slate-400 transition hover:bg-slate-800 hover:text-white"
          >
            <X size={20} />
          </button>
        </div>

        {/* Content */}
        <div className="p-6">
          {loading && (
            <div className="flex flex-col items-center justify-center py-16">
              <Loader2 className="h-12 w-12 animate-spin text-brand-light" />
              <p className="mt-4 text-lg text-slate-300">
                ИИ придумывает идею и пишет сценарий...
              </p>
              <p className="mt-2 text-sm text-slate-500">
                Это может занять несколько секунд
              </p>
            </div>
          )}

          {error && (
            <div className="rounded-xl border border-red-500/30 bg-red-900/20 p-6">
              <p className="mb-4 text-red-200">{error}</p>
              <button
                type="button"
                onClick={handleGenerate}
                className="flex items-center gap-2 rounded-xl bg-red-600 px-4 py-2 text-sm font-semibold text-white transition hover:bg-red-700"
              >
                <RefreshCw size={16} />
                Повторить
              </button>
            </div>
          )}

          {/* Старый формат (для обратной совместимости) */}
          {result && !loading && (
            <div className="space-y-6">
              {/* Idea Section */}
              <div className="rounded-xl border border-white/10 bg-slate-800/40 p-6">
                <h3 className="mb-3 flex items-center gap-2 text-lg font-semibold text-brand-light">
                  <Sparkles size={20} />
                  Идея ролика
                </h3>
                <p className="text-slate-200 whitespace-pre-wrap">
                  {result.idea}
                </p>
              </div>

              {/* Scripts Section */}
              <div className="space-y-4">
                <h3 className="text-lg font-semibold text-white">Сценарии:</h3>
                {result.scripts.map((script, index) => (
                  <div
                    key={index}
                    className="relative rounded-xl border border-white/10 bg-slate-800/40 p-6"
                  >
                    <div className="mb-3 flex items-center justify-between gap-2">
                      <span className="rounded-full bg-brand/20 px-3 py-1 text-sm font-semibold text-brand-light">
                        Сценарий {index + 1}
                      </span>
                      <button
                        type="button"
                        onClick={() => handleCopyScript(script, index)}
                        className="flex items-center gap-2 rounded-lg border border-white/10 bg-slate-700/50 px-3 py-1.5 text-xs font-medium text-slate-200 transition hover:border-brand/40 hover:bg-slate-700 hover:text-white"
                        title="Копировать сценарий"
                      >
                        {copiedScriptIndex === index ? (
                          <>
                            <Check size={14} className="text-green-400" />
                            <span className="text-green-400">Скопировано</span>
                          </>
                        ) : (
                          <>
                            <Copy size={14} />
                            <span>Копировать</span>
                          </>
                        )}
                      </button>
                    </div>
                    <p className="text-slate-200 whitespace-pre-wrap">
                      {script}
                    </p>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Новый формат (детальные сценарии) */}
          {detailedResult && !loading && (
            <div className="space-y-6">
              {/* Scripts Section - показываем только если есть сценарии и режим не video-prompt-only */}
              {detailedResult.scenarios.length > 0 &&
                detailedResult.mode !== "video-prompt-only" && (
                  <div className="space-y-4">
                    <h3 className="text-lg font-semibold text-white">Сценарии:</h3>
                    {detailedResult.scenarios.map((scenario, scenarioIndex) => {
                  const scenarioText = `${scenario.title} (${scenario.durationSeconds} сек):\n\n${scenario.steps
                    .map(
                      (step) =>
                        `${step.secondFrom}-${step.secondTo}с: ${step.description}${step.dialog.length > 0 ? `\n${step.dialog.map((d) => `${d.character}: "${d.text}"`).join("\n")}` : ""}`
                    )
                    .join("\n\n")}`;

                  return (
                    <div
                      key={scenarioIndex}
                      className="relative rounded-xl border border-white/10 bg-slate-800/40 p-6"
                    >
                      <div className="mb-4 flex items-center justify-between gap-2">
                        <div>
                          <h4 className="text-lg font-semibold text-brand-light">
                            {scenario.title}
                          </h4>
                          <span className="mt-1 inline-block rounded-full bg-brand/20 px-2 py-0.5 text-xs font-semibold text-brand-light">
                            {scenario.durationSeconds} сек
                          </span>
                        </div>
                        <button
                          type="button"
                          onClick={() =>
                            handleCopyScript(scenarioText, scenarioIndex)
                          }
                          className="flex items-center gap-2 rounded-lg border border-white/10 bg-slate-700/50 px-3 py-1.5 text-xs font-medium text-slate-200 transition hover:border-brand/40 hover:bg-slate-700 hover:text-white"
                          title="Копировать сценарий"
                        >
                          {copiedScriptIndex === scenarioIndex ? (
                            <>
                              <Check size={14} className="text-green-400" />
                              <span className="text-green-400">Скопировано</span>
                            </>
                          ) : (
                            <>
                              <Copy size={14} />
                              <span>Копировать</span>
                            </>
                          )}
                        </button>
                      </div>

                      <div className="space-y-3">
                        {scenario.steps.map((step, stepIndex) => (
                          <div
                            key={stepIndex}
                            className="rounded-lg border border-white/5 bg-slate-900/40 p-4"
                          >
                            <div className="mb-2 flex items-center gap-2">
                              <span className="rounded bg-brand/20 px-2 py-1 text-xs font-semibold text-brand-light">
                                {step.secondFrom}-{step.secondTo}с
                              </span>
                            </div>
                            <p className="mb-2 text-sm text-slate-200">
                              {step.description}
                            </p>
                            {step.dialog.length > 0 && (
                              <div className="mt-3 space-y-1 border-t border-white/5 pt-3">
                                {step.dialog.map((line, dialogIndex) => (
                                  <div
                                    key={dialogIndex}
                                    className="text-sm text-slate-300"
                                  >
                                    <span className="font-semibold text-brand-light">
                                      {line.character}:
                                    </span>{" "}
                                    <span className="italic">"{line.text}"</span>
                                  </div>
                                ))}
                              </div>
                            )}
                          </div>
                        ))}
                      </div>
                    </div>
                  );
                    })}
                  </div>
                )}

              {/* Сообщение для режима video-prompt-only, если нет сценариев */}
              {detailedResult.mode === "video-prompt-only" &&
                detailedResult.scenarios.length === 0 && (
                  <div className="rounded-xl border border-white/10 bg-slate-900/60 p-6 text-center">
                    <p className="text-slate-400">
                      В этом режиме сценарий не генерируется, только промпт для видео.
                    </p>
                  </div>
                )}

              {/* Блок названия файла (для режима video-prompt-only) */}
              {detailedResult.fileTitle && (
                <div className="mb-4 rounded-xl border border-slate-700 bg-slate-800/60 px-4 py-3">
                  <div className="flex items-center justify-between gap-3">
                    <div className="flex-1 min-w-0">
                      <div className="mb-1 text-xs uppercase tracking-wide text-slate-400">
                        Название ролика / файла
                      </div>
                      <div className="break-all text-sm font-medium text-slate-50">
                        {detailedResult.fileTitle}
                      </div>
                    </div>
                    <button
                      type="button"
                      onClick={handleCopyFileTitle}
                      disabled={!detailedResult.fileTitle}
                      className="shrink-0 flex items-center gap-1.5 rounded-lg bg-brand px-3 py-1.5 text-xs font-medium text-white transition hover:bg-brand-dark disabled:cursor-not-allowed disabled:opacity-50"
                    >
                      {copiedFileTitle ? (
                        <>
                          <Check size={14} />
                          <span>Скопировано</span>
                        </>
                      ) : (
                        <>
                          <Copy size={14} />
                          <span>Копировать</span>
                        </>
                      )}
                    </button>
                  </div>
                </div>
              )}

              {/* VIDEO_PROMPT блок (для режимов "prompt" и "video-prompt-only") */}
              {detailedResult.videoPrompt && (
                <div className="rounded-xl border border-brand/30 bg-brand/5 p-6">
                  <div className="mb-4 flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between">
                    <h3 className="text-lg font-semibold text-brand-light">
                      🎬 Промпт для генерации видео
                    </h3>
                    <div className="flex flex-wrap items-center gap-2">
                      <button
                        type="button"
                        onClick={handleCopyVideoPrompt}
                        className="flex items-center gap-2 rounded-lg border border-brand/30 bg-brand/10 px-3 py-1.5 text-xs font-medium text-brand-light transition hover:bg-brand/20"
                      >
                        <Copy size={14} />
                        {copiedVideoPrompt ? "Скопировано!" : "Копировать"}
                      </button>
                      <button
                        type="button"
                        onClick={handleSendToSyntx}
                        disabled={syntxSendStatus === "loading"}
                        className="flex items-center gap-2 rounded-lg border border-emerald-500/30 bg-emerald-500/10 px-3 py-1.5 text-xs font-medium text-emerald-300 transition hover:bg-emerald-500/20 disabled:opacity-50 disabled:cursor-not-allowed"
                      >
                        {syntxSendStatus === "loading" ? (
                          <>
                            <Loader2 size={14} className="animate-spin" />
                            Отправка...
                          </>
                        ) : syntxSendStatus === "sent" ? (
                          <>
                            <Check size={14} />
                            Отправлено ✔
                          </>
                        ) : (
                          <>
                            <Sparkles size={14} />
                            Отправить в SyntX
                          </>
                        )}
                      </button>
                      {syntxSendStatus === "sent" && (
                        <button
                          type="button"
                          onClick={handleFetchVideoToDrive}
                          disabled={driveStatus === "loading"}
                          className="flex items-center gap-2 rounded-lg border border-white/20 bg-slate-900/60 px-3 py-1.5 text-xs font-medium text-slate-100 transition hover:border-brand/40 hover:bg-slate-800 disabled:opacity-50 disabled:cursor-not-allowed"
                        >
                          {driveStatus === "loading" ? (
                            <>
                              <Loader2 size={14} className="animate-spin" />
                              Забираем видео...
                            </>
                          ) : driveStatus === "success" ? (
                            <>
                              <Check size={14} />
                              Видео на сервере
                            </>
                          ) : (
                            <>
                              <Sparkles size={14} />
                              Забрать видео из SyntX на сервер
                            </>
                          )}
                        </button>
                      )}
                    </div>
                  </div>
                  <textarea
                    readOnly
                    value={detailedResult.videoPrompt}
                    rows={12}
                    className="w-full rounded-lg border border-white/10 bg-slate-950/60 px-4 py-3 text-sm text-slate-200 outline-none"
                  />
                  {syntxSendStatus === "sent" && !syntxError && (
                    <p className="mt-2 text-xs text-emerald-300">
                      ✓ Промпт успешно отправлен в SyntX через Telegram
                    </p>
                  )}
                  {syntxSendStatus === "error" && syntxError && (
                    <p className="mt-2 text-xs text-red-300">{syntxError}</p>
                  )}
                  {syntxSendStatus === "idle" && (
                    <p className="mt-2 text-xs text-slate-400">
                      Готовый промпт для Sora / Veo 3.1 Fast. Скопируйте и
                      используйте для генерации видео или отправьте в SyntX.
                    </p>
                  )}
                  {driveStatus === "success" && driveMessage && (
                    <p className="mt-2 text-xs text-emerald-300">
                      {driveMessage}
                    </p>
                  )}
                  {driveStatus === "error" && driveMessage && (
                    <p className="mt-2 text-xs text-red-300">{driveMessage}</p>
                  )}
                  {driveStatus === "telegram_session_invalid" && (
                    <div className="mt-2 rounded-lg border border-amber-500/30 bg-amber-900/20 p-3">
                      <p className="text-xs text-amber-300">{driveMessage}</p>
                      <button
                        type="button"
                        onClick={() => navigate("/settings")}
                        className="mt-2 rounded-lg bg-amber-500/20 px-3 py-1.5 text-xs font-medium text-amber-300 transition hover:bg-amber-500/30"
                      >
                        Перейти в настройки аккаунта
                      </button>
                    </div>
                  )}
                </div>
              )}
            </div>
          )}

          {/* Action Buttons */}
          {(result || detailedResult) && !loading && (
            <div className="mt-6 flex flex-wrap gap-3 border-t border-white/10 pt-6">
              <button
                type="button"
                onClick={handleCopyAll}
                className="flex items-center gap-2 rounded-xl bg-brand px-5 py-3 text-sm font-semibold text-white transition hover:bg-brand-dark"
              >
                {copied ? (
                  <>
                    <Check size={16} />
                    Скопировано!
                  </>
                ) : (
                  <>
                    <Copy size={16} />
                    Копировать всё
                  </>
                )}
              </button>
              <button
                type="button"
                onClick={handleGenerate}
                disabled={loading}
                className="flex items-center gap-2 rounded-xl border border-white/10 bg-slate-800/60 px-5 py-3 text-sm font-semibold text-slate-200 transition hover:border-brand/40 hover:text-white disabled:cursor-not-allowed disabled:opacity-50"
              >
                <RefreshCw size={16} className={loading ? "animate-spin" : ""} />
                Перегенерировать
              </button>
              <button
                type="button"
                onClick={onClose}
                className="ml-auto rounded-xl border border-white/10 bg-slate-800/60 px-5 py-3 text-sm font-semibold text-slate-200 transition hover:border-brand/40 hover:text-white"
              >
                Закрыть
              </button>
            </div>
          )}
        </div>
      </div>
    </div>
  );
};

export default AIAutoGenerateModal;

